image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  IMAGE_BACKEND: registry.gitlab.com/mon-projet/backend
  IMAGE_FRONTEND: registry.gitlab.com/mon-projet/frontend

build_backend:
  stage: build
  script:
    - docker build -t $IMAGE_BACKEND ./backend
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $IMAGE_BACKEND

build_frontend:
  stage: build
  script:
    - docker build -t $IMAGE_FRONTEND ./frontend
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $IMAGE_FRONTEND
