stages:
  - build
  - test
  - deploy

build-backend:
  stage: build
  script:
    - cd backend
    - npm install
    - echo "Backend built!"

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

test-backend:
  stage: test
  script:
    - echo "Tests Backend"

deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours..."
