services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://root:example@mongo:27017/ecommerce?authSource=admin"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
