apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tinhine/my-backend:latest  # Image Docker depuis Docker Hub
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://root:example@mongo-service:27017/ecommerce?authSource=admin"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Service interne pour le frontend